### ISSUE TITLE
The magic is not recognized correctly.

### ISSUE THREAD

**Issue by kagekiyo7** [OSPG/binwalk#27]
I think the magic is correct, but nothing is detected. If I delete the second line, it is detected, so I think this is the cause.
I would appreciate it if you could help me solve the problem.
- binwalk: latest verion, OS: Ubuntu (WSL2)

[sample.zip](https://github.com/user-attachments/files/17375239/sample.zip)

` binwalk -m=[path to magic]  [path to target]`

**Comment by stkw0** [comment]
When using "string  x" it will match as many characters as there are until it finds a newline, a null character or if strlen has been specified. 
In this specific case, it takes the last \xFF as part of the string. To work around that, you can specify {strlen:4} before reading the version string. A magic like the next one will work:

```
0       string   \xCC\xDDDL_FS     Datalight FlashFX FTL{strlen:4},
>0x7    string   x                 Version {string}%s
>0xB    string   !\xFF\xFF\xFF\xFF\xFF     {invalid}
```

**Comment by kagekiyo7** [comment]
Thank you! I see, I understand the reason.
I will use that method.

There is another magic that is not being recognized and I don't know the cause. Can you also help solve this? (0x300000)
[sample2.zip](https://github.com/user-attachments/files/17430856/sample2.zip)

**Comment by stkw0** [comment]
Why it have a negative offset? Maybe you intended to do >1? But in that case it could be only "1" as the ">" is the indentation

**Comment by kagekiyo7** [comment]
That's because the first `\xFF` is not actually part of the magic, but is added to prevent false positives.
So the actual magic is `\x7E\x00\x00\xEA`.

**Comment by kagekiyo7** [comment]
[target2.zip](https://github.com/user-attachments/files/17432110/target2.zip)

What I find strange is that, in this case, it is recognized.

**Comment by stkw0** [comment]
> That's because the first `\xFF` is not actually part of the magic, but is added to prevent false positives. So the actual magic is `\x7E\x00\x00\xEA`.

If the file starts with a 0xff you can match that byte first and then the rest of the string

**Comment by kagekiyo7** [comment]
Do you know why [A](https://github.com/OSPG/binwalk/issues/27#issuecomment-2421971150) is recognized but [B](https://github.com/OSPG/binwalk/issues/27#issuecomment-2421971150) is not?
Well, if -1 is not officially supported, I will avoid it.

**Comment by stkw0** [comment]
I think that libmagic supports it, so it would make sense to support it here too. Maybe you could do
```
0      string	\x7E\x00\x00\xEA  EPOC32 ROM
>-1	byte	=255
```

**Comment by kagekiyo7** [comment]
Thank you.
