### ISSUE TITLE
About EOL

### ISSUE THREAD

**Issue by kagekiyo7** [OSPG/binwalk#28]
Thank you for all your hard work maintaining v2!

If it’s okay, could you archive the repository instead of deleting it?
The v3 is great, but I have a magic file that I wrote, and I only use it in dump files for a specific field, so I still need to use v2.

**Comment by stkw0** [comment]
Yes, that was the plan. Only if the existence of this fork makes people confused I would remove it, which I don't think would be a major problem. 

In any case, there is a lot of time until that. If you need help porting this magic file to v3 you could open an issue to the original repo.
