### ISSUE TITLE
Change url and deps.sh of the jefferson

### ISSUE THREAD

**Issue by shiren00** [OSPG/binwalk#6]
Hi. Thank you for the nice maintenance!

jefferson's description as follows
https://github.com/sviehb/jefferson

> Jefferson is now maintained and released from https://github.com/onekey-sec/jefferson/.
> 
> This repository should not be relied upon to install Jefferson. We recommend you either clone from https://github.com/onekey-sec/jefferson/ or install from pip using pip install --user jefferson.

**Comment by stkw0** [comment]
Thank you very much for the notice!
